### PR TITLE
v3.0 Major release

### PR DESCRIPTION
**Pull request by aduth**
This Pull Request collects the breaking changes intended for the v3.0 Major release.

It includes:
### remove the now-unused `no-lodash-import` rule

Related: https://github.com/Automattic/eslint-config-wpcalypso/commit/b796bcec348799f36f66390ae5c93578d1200f8c

This pull request seeks to remove the now-unused `no-lodash-import` rule, dropped in favor of using [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) to transform root Lodash imports. This is a breaking change and as such, has been added to a v3.0.0 milestone.
### remove the superseded `i18n-no-newlines` rule

The new `i18n-no-collapsible-whitespace` rule covers all the cases that `i18n-no-newlines` did and is conceptually sounder, so we're going to drop newlines.

### CODE REVIEW

**Comment by deBhal** [comment]
The `no-lodash-import` changes look good 👍 , and I've added the change to remove the `i18n-no-newlines rule` as we discussed.

I've also updated the name and your comment to reflect that it's our home for v3.0

I had a think about it and a bit of reading, and I think the way to do this with a bit more process would have been to open a v3.0 branch, and open these two changes as separate PRs against that branch - the  [gitflow model](https://gitversion.readthedocs.io/en/latest/git-branching-strategies/gitflow-examples/).

That way, we could commit the PRs as soon as we recognize that we'll want them, and merge the respective PRs into the v3 branch, and then the actual major release itself is a PR from the v3 branch onto master.

I think this project and release is small enough that it's fine to do the release in a single PR, but I think we'd want some more structure if it was even a little bit bigger.

What do you think?

**Comment by aduth** [comment]
What's the downside to merging changes separately into the master branch, even breaking changes? So long we don't publish a release to npm, it doesn't seem like it'd be a problem for dependent projects.

**Comment by deBhal** [comment]
> So long we don't publish a release to npm

Just that.  If we merged one of the breaking changes today, and tomorrow we want to release a bugfix we're in a position where we have to do the major release to get a minor release out, and then we'd need another major release for the jsx classname issue rule.

That's not the end of the world, it just bugs me a little to have the concerns mixed like that.

A major version branch gives you a place to gather up the changes related to the major version without blocking anything while you do it. That means you can have a different cadence for major and minor releases if you want.

As long as you merge it back into master for the release.  Please let's not start supporting earlier versions :)

Edit:  The real cost of a "forced" major release probably isn't us/this project, but for dependent projects if they want the fixes but updating for the breaking changes is inconvenient.

**Comment by aduth** [comment]
> want to release a bugfix we're in a position where we have to do the major release to get a minor release out

Yeah, that's a good point. I guess the project isn't updated frequently enough that it's been a problem that we've encountered thus far, but would certainly be a non-ideal scenario to work through if it were to arise.

I'll plan to do some more reading on gitflow in the morning. Only issue that comes to mind do we / how do we keep the major version branch up to date with changes from master.

Would you recommend then that we push a new minor or patch release for the jsx-classname-namespace fix separate from the breaking changes?

**Comment by deBhal** [comment]
> Would you recommend then that we push a new minor or patch release for the jsx-classname-namespace fix separate from the breaking changes?

No, I'm not a fan of process for it's own sake :) In this case we're protected twice - first by npm, and then again by `eslint-config-wpcalypso`, so we know that it'll be fine to release all 3 changes together.

I think merging is a reasonable enough risk here that I wish I'd opened a separate PR instead of hijacking this one :)

> do we / how do we keep the major version branch up to date with changes from master.

We'd definitely want to rebase the major release branch against master before merging it, and whenever it was convenient like any other branch/PR. I would think you'd rebase it every time you added more commits to it, for example, or if you made a change to master that you thought might cause a conflict.

If we were doing the release branch for this PR we'd consider rebasing when we made any changes to the rules we're dropping.  They'd be pretty easy conflicts to resolve, though, so we might just rebase before we ship the major version bump.

**Pull request merged**
